# General
spring:
  application:
    name: api-sms-sender

# OpenAPI 
openapi:
  name: api-service-sms-sender
  title: SmsSender
  version: '@project.version@'

scheduler:
  linkmobility:
    health:
      cron: "-" # Disabled by default
